import { Menu } from '@/api/types';

export const menu_data: Menu = {
  start_date: '2025-09-01',
  last_updated: '',
  days: [
    {
      date: '2025-08-31',
      menu_items: [],
    },
    {
      date: '2025-09-01',
      menu_items: [
        {
          is_section_title: false,
          is_holiday: true,
          no_line_break: false,
          text: 'Labor Day',
          food: null,
          category: null,
          serving_size_amount: null,
          serving_size_unit: null,
        },
      ],
    },
    {
      date: '2025-09-02',
      menu_items: [
        {
          is_section_title: true,
          is_holiday: false,
          no_line_break: false,
          text: 'Pick One Entree',
          food: null,
          category: null,
          serving_size_amount: null,
          serving_size_unit: null,
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Hot Dog on a Bun',
            description: '',
            image_url: 'https://assets.nutrislice.com/asset/serve/image/jpg/204366/thumbnail2',
            food_category: 'entree',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 280.0,
              g_fat: 11.0,
              g_saturated_fat: 3.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 35.0,
              g_carbs: 33.0,
              g_added_sugar: null,
              g_sugar: 7.0,
              mg_potassium: null,
              mg_sodium: 840.0,
              g_fiber: 4.0,
              g_protein: 13.0,
              mg_iron: 2.4,
              mg_calcium: 110.0,
              mg_vitamin_c: 2.0,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Grain',
                  help_text: 'This contains grain',
                  sort_order: 2,
                },
                {
                  name: 'Protein',
                  help_text: 'This contains protein',
                  sort_order: 3,
                },
              ],
            },
          },
          category: 'entree',
          serving_size_amount: 60.0,
          serving_size_unit: 'eah',
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Deli Ham and Cheese  on a Bun',
            description: '',
            image_url: 'https://assets.nutrislice.com/asset/serve/image/jpg/202955/thumbnail2',
            food_category: 'entree',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 240.0,
              g_fat: 10.0,
              g_saturated_fat: 3.5,
              g_trans_fat: 0.0,
              mg_cholesterol: 57.0,
              g_carbs: 23.0,
              g_added_sugar: null,
              g_sugar: 5.0,
              mg_potassium: null,
              mg_sodium: 790.0,
              g_fiber: 3.0,
              g_protein: 17.0,
              mg_iron: 1.5,
              mg_calcium: 130.0,
              mg_vitamin_c: 1.0,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Grain',
                  help_text: 'This contains grain',
                  sort_order: 2,
                },
                {
                  name: 'Protein',
                  help_text: 'This contains protein',
                  sort_order: 3,
                },
              ],
            },
          },
          category: 'entree',
          serving_size_amount: 7.0,
          serving_size_unit: 'each',
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: "Smucker's SB & J",
            description: '',
            image_url: null,
            food_category: '',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 310.0,
              g_fat: 15.0,
              g_saturated_fat: 2.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 0.0,
              g_carbs: 33.0,
              g_added_sugar: null,
              g_sugar: 11.0,
              mg_potassium: null,
              mg_sodium: 300.0,
              g_fiber: 4.0,
              g_protein: 9.0,
              mg_iron: null,
              mg_calcium: null,
              mg_vitamin_c: null,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [],
            },
          },
          category: null,
          serving_size_amount: 1.0,
          serving_size_unit: 'each',
        },
        {
          is_section_title: true,
          is_holiday: false,
          no_line_break: false,
          text: 'Fruit & Vegetable Sides',
          food: null,
          category: null,
          serving_size_amount: null,
          serving_size_unit: null,
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Steamed Corn',
            description: 'Golden bites of corn have fiber, folate, and fuel for your body!',
            image_url:
              'https://client-food-images.nutrislice.com/images/Yh/YhPuT9anRwPGGYG9CLHk5R/1489180670_526574__2015-nutrislice-side-ALT1-corn-1920x1080.jpg.1024x0_q85.jpg',
            food_category: '',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 90.0,
              g_fat: 0.5,
              g_saturated_fat: 0.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 0.0,
              g_carbs: 22.0,
              g_added_sugar: null,
              g_sugar: 2.0,
              mg_potassium: null,
              mg_sodium: 0.0,
              g_fiber: 2.0,
              g_protein: 3.0,
              mg_iron: 0.0,
              mg_calcium: 0.0,
              mg_vitamin_c: 0.0,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Vegetable',
                  help_text: 'This contains vegetables',
                  sort_order: 4,
                },
              ],
            },
          },
          category: null,
          serving_size_amount: 45.0,
          serving_size_unit: '1/2 cup',
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Fresh Broccoli',
            description: 'Broccoli is filled with Iron to keep you filled with energy throughout the day!',
            image_url:
              'https://client-food-images.nutrislice.com/images/5i/5ibstsYyn4wKNfhJyLpQqR/1489178244_466239__2015-nutrislice-side-steamed-broccoli-1920x1080.jpg.1024x0_q85.jpg',
            food_category: '',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 15.0,
              g_fat: 0.0,
              g_saturated_fat: 0.0,
              g_trans_fat: null,
              mg_cholesterol: 0.0,
              g_carbs: 3.0,
              g_added_sugar: null,
              g_sugar: null,
              mg_potassium: null,
              mg_sodium: 15.0,
              g_fiber: 1.0,
              g_protein: 1.0,
              mg_iron: 0.3,
              mg_calcium: 20.0,
              mg_vitamin_c: 37.0,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Vegetable',
                  help_text: 'This contains vegetables',
                  sort_order: 4,
                },
              ],
            },
          },
          category: null,
          serving_size_amount: 65.0,
          serving_size_unit: '1/2 cup',
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Fresh Sliced Apples',
            description:
              'Packed with Fiber, Apple Slices keep your stomach full and your energy steady to stay focused all day!',
            image_url: 'https://assets.nutrislice.com/asset/serve/image/jpg/21728/thumbnail2',
            food_category: '',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 60.0,
              g_fat: 0.0,
              g_saturated_fat: 0.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 0.0,
              g_carbs: 16.0,
              g_added_sugar: null,
              g_sugar: 12.0,
              mg_potassium: null,
              mg_sodium: 0.0,
              g_fiber: 4.0,
              g_protein: 0.0,
              mg_iron: 0.0,
              mg_calcium: 0.0,
              mg_vitamin_c: 5.0,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Fruit',
                  help_text: 'This contains fruit',
                  sort_order: 1,
                },
              ],
            },
          },
          category: null,
          serving_size_amount: 40.0,
          serving_size_unit: '1/2 cup',
        },
      ],
    },
    {
      date: '2025-09-03',
      menu_items: [
        {
          is_section_title: true,
          is_holiday: false,
          no_line_break: false,
          text: 'Pick One Entree',
          food: null,
          category: null,
          serving_size_amount: null,
          serving_size_unit: null,
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Pancakes',
            description: '',
            image_url:
              'https://client-food-images.nutrislice.com/images/TE/TExdevnDMXqQiRxc74ZGwA/1489182814_902697__2015-nutrislice-breakfast-ALT3-pancakes-1920x1080.jpg.1024x0_q85.jpg',
            food_category: 'entree',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 160.0,
              g_fat: 3.0,
              g_saturated_fat: 0.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 10.0,
              g_carbs: 30.0,
              g_added_sugar: null,
              g_sugar: null,
              mg_potassium: null,
              mg_sodium: 220.0,
              g_fiber: 2.0,
              g_protein: 4.0,
              mg_iron: 1.4,
              mg_calcium: 40.0,
              mg_vitamin_c: null,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Grain',
                  help_text: 'This contains grain',
                  sort_order: 2,
                },
              ],
            },
          },
          category: 'entree',
          serving_size_amount: 72.0,
          serving_size_unit: '2 pancake',
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: true,
          text: 'w/',
          food: null,
          category: null,
          serving_size_amount: null,
          serving_size_unit: null,
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: true,
          text: '',
          food: {
            name: 'Pork Sausage Patty',
            description: '',
            image_url:
              'https://client-food-images.nutrislice.com/images/aX/aXGyCRXDMT5fWayq6Pi7p5/1489180287_93089__2015-nutrislice-breakfast-ALT1-sausage-patties-1920x1080.jpg.1024x0_q85.jpg',
            food_category: 'entree',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 230.0,
              g_fat: 22.0,
              g_saturated_fat: 8.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 45.0,
              g_carbs: 1.0,
              g_added_sugar: null,
              g_sugar: 1.0,
              mg_potassium: null,
              mg_sodium: 370.0,
              g_fiber: 0.0,
              g_protein: 7.0,
              mg_iron: 0.8,
              mg_calcium: 20.0,
              mg_vitamin_c: 0.0,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Protein',
                  help_text: 'This contains protein',
                  sort_order: 3,
                },
              ],
            },
          },
          category: 'entree',
          serving_size_amount: 100.0,
          serving_size_unit: 'each',
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'SB & J Sandwich w/ String Cheese',
            description: '',
            image_url: 'https://assets.nutrislice.com/asset/serve/image/jpg/204744/thumbnail2',
            food_category: 'entree',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 490.0,
              g_fat: 25.0,
              g_saturated_fat: 6.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 20.0,
              g_carbs: 50.0,
              g_added_sugar: null,
              g_sugar: 19.0,
              mg_potassium: null,
              mg_sodium: 570.0,
              g_fiber: 6.0,
              g_protein: 19.0,
              mg_iron: 3.4,
              mg_calcium: 270.0,
              mg_vitamin_c: null,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Grain',
                  help_text: 'This contains grain',
                  sort_order: 2,
                },
                {
                  name: 'Protein',
                  help_text: 'This contains protein',
                  sort_order: 3,
                },
              ],
            },
          },
          category: 'entree',
          serving_size_amount: 1.0,
          serving_size_unit: 'each',
        },
        {
          is_section_title: true,
          is_holiday: false,
          no_line_break: false,
          text: 'Fruit & Vegetable Sides',
          food: null,
          category: null,
          serving_size_amount: null,
          serving_size_unit: null,
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Cucumber Slices',
            description:
              'Cucumber slices are packed with hydration and Potassium to keep your muscles strong and moving!',
            image_url:
              'https://client-food-images.nutrislice.com/images/4e/4eNizm9UqXPVxuMsd8tFSV/1489162879_657444__2015-nutrislice-side-cucumber-slices-1920x1080.jpg.1024x0_q85.jpg',
            food_category: '',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 10.0,
              g_fat: 0.0,
              g_saturated_fat: 0.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 0.0,
              g_carbs: 3.0,
              g_added_sugar: null,
              g_sugar: 1.0,
              mg_potassium: null,
              mg_sodium: 0.0,
              g_fiber: 0.0,
              g_protein: 0.0,
              mg_iron: 0.2,
              mg_calcium: 10.0,
              mg_vitamin_c: 2.0,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Vegetable',
                  help_text: 'This contains vegetables',
                  sort_order: 4,
                },
              ],
            },
          },
          category: null,
          serving_size_amount: 62.0,
          serving_size_unit: '1/2 cup',
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Potato Triangle',
            description: '',
            image_url: null,
            food_category: '',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 120.0,
              g_fat: 5.0,
              g_saturated_fat: 1.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 0.0,
              g_carbs: 17.0,
              g_added_sugar: null,
              g_sugar: 0.0,
              mg_potassium: null,
              mg_sodium: 350.0,
              g_fiber: 2.0,
              g_protein: 2.0,
              mg_iron: null,
              mg_calcium: null,
              mg_vitamin_c: null,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Vegetable',
                  help_text: 'This contains vegetables',
                  sort_order: 4,
                },
              ],
            },
          },
          category: null,
          serving_size_amount: 1.0,
          serving_size_unit: 'each',
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Orange Juice',
            description: '',
            image_url: 'https://assets.nutrislice.com/asset/serve/image/jpg/204514/thumbnail2',
            food_category: '',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 50.0,
              g_fat: 0.0,
              g_saturated_fat: 0.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 0.0,
              g_carbs: 12.0,
              g_added_sugar: 0.0,
              g_sugar: 10.0,
              mg_potassium: null,
              mg_sodium: 10.0,
              g_fiber: 1.0,
              g_protein: 1.0,
              mg_iron: 0.0,
              mg_calcium: 0.0,
              mg_vitamin_c: 30.0,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Fruit',
                  help_text: 'This contains fruit',
                  sort_order: 1,
                },
              ],
            },
          },
          category: null,
          serving_size_amount: 1.0,
          serving_size_unit: 'each',
        },
      ],
    },
    {
      date: '2025-09-04',
      menu_items: [
        {
          is_section_title: true,
          is_holiday: false,
          no_line_break: false,
          text: 'Pick One Entree',
          food: null,
          category: null,
          serving_size_amount: null,
          serving_size_unit: null,
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Cheese Quesadilla',
            description: '',
            image_url:
              'https://client-food-images.nutrislice.com/images/Gc/GcmVbfhr6JpWbz8UfeMmcd/1489085476_781305__2015-nutrislice-entree-quesadilla-1920x1080.jpg.1024x0_q85.jpg',
            food_category: 'entree',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 300.0,
              g_fat: 10.0,
              g_saturated_fat: 3.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 10.0,
              g_carbs: 39.0,
              g_added_sugar: null,
              g_sugar: 3.0,
              mg_potassium: null,
              mg_sodium: 670.0,
              g_fiber: 4.0,
              g_protein: 16.0,
              mg_iron: 2.7,
              mg_calcium: 200.0,
              mg_vitamin_c: 0.0,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Grain',
                  help_text: 'This contains grain',
                  sort_order: 2,
                },
                {
                  name: 'Protein',
                  help_text: 'This contains protein',
                  sort_order: 3,
                },
              ],
            },
          },
          category: 'entree',
          serving_size_amount: 1.0,
          serving_size_unit: 'each',
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Deli Turkey & Cheese  on a Bun',
            description: '',
            image_url: 'https://assets.nutrislice.com/asset/serve/image/jpg/203887/thumbnail2',
            food_category: 'entree',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 230.0,
              g_fat: 8.0,
              g_saturated_fat: 2.5,
              g_trans_fat: 0.0,
              mg_cholesterol: 41.0,
              g_carbs: 24.0,
              g_added_sugar: null,
              g_sugar: 5.0,
              mg_potassium: null,
              mg_sodium: 790.0,
              g_fiber: 3.0,
              g_protein: 20.0,
              mg_iron: 1.0,
              mg_calcium: 130.0,
              mg_vitamin_c: null,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Grain',
                  help_text: 'This contains grain',
                  sort_order: 2,
                },
                {
                  name: 'Protein',
                  help_text: 'This contains protein',
                  sort_order: 3,
                },
              ],
            },
          },
          category: 'entree',
          serving_size_amount: 284.0,
          serving_size_unit: 'each',
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: "Smucker's SB & J",
            description: '',
            image_url: null,
            food_category: '',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 310.0,
              g_fat: 15.0,
              g_saturated_fat: 2.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 0.0,
              g_carbs: 33.0,
              g_added_sugar: null,
              g_sugar: 11.0,
              mg_potassium: null,
              mg_sodium: 300.0,
              g_fiber: 4.0,
              g_protein: 9.0,
              mg_iron: null,
              mg_calcium: null,
              mg_vitamin_c: null,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [],
            },
          },
          category: null,
          serving_size_amount: 1.0,
          serving_size_unit: 'each',
        },
        {
          is_section_title: true,
          is_holiday: false,
          no_line_break: false,
          text: 'Fruit & Vegetable Sides',
          food: null,
          category: null,
          serving_size_amount: null,
          serving_size_unit: null,
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Refried Beans',
            description: 'Refried and ready! Packed with fiber, protein, and iron for lasting energy!',
            image_url: 'https://assets.nutrislice.com/asset/serve/image/jpg/204639/thumbnail2',
            food_category: '',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 180.0,
              g_fat: 5.0,
              g_saturated_fat: 2.5,
              g_trans_fat: 0.0,
              mg_cholesterol: 8.0,
              g_carbs: 23.0,
              g_added_sugar: null,
              g_sugar: 0.0,
              mg_potassium: null,
              mg_sodium: 590.0,
              g_fiber: 9.0,
              g_protein: 9.0,
              mg_iron: 2.0,
              mg_calcium: 60.0,
              mg_vitamin_c: null,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Vegetable',
                  help_text: 'This contains vegetables',
                  sort_order: 4,
                },
              ],
            },
          },
          category: null,
          serving_size_amount: 42.0,
          serving_size_unit: '1/2 cup',
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Celery Sticks',
            description: '',
            image_url:
              'https://client-food-images.nutrislice.com/images/Te/TezdPHHWCVHevgQmEAe6jZ/1489084800_597447__2015-nutrislice-side-celery-1920x1080.jpg.1024x0_q85.jpg',
            food_category: '',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 10.0,
              g_fat: 0.0,
              g_saturated_fat: 0.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 0.0,
              g_carbs: 2.0,
              g_added_sugar: null,
              g_sugar: 1.0,
              mg_potassium: null,
              mg_sodium: 55.0,
              g_fiber: 1.0,
              g_protein: 0.0,
              mg_iron: 0.1,
              mg_calcium: 30.0,
              mg_vitamin_c: 2.0,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Vegetable',
                  help_text: 'This contains vegetables',
                  sort_order: 4,
                },
              ],
            },
          },
          category: null,
          serving_size_amount: 61.0,
          serving_size_unit: '1/2 cup',
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Cinnamon Applesauce',
            description: '',
            image_url: 'https://assets.nutrislice.com/asset/serve/image/jpg/202906/thumbnail2',
            food_category: '',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 70.0,
              g_fat: 0.0,
              g_saturated_fat: 0.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 0.0,
              g_carbs: 19.0,
              g_added_sugar: null,
              g_sugar: 15.0,
              mg_potassium: null,
              mg_sodium: 0.0,
              g_fiber: 2.0,
              g_protein: 0.0,
              mg_iron: 0.0,
              mg_calcium: 0.0,
              mg_vitamin_c: 0.0,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Fruit',
                  help_text: 'This contains fruit',
                  sort_order: 1,
                },
              ],
            },
          },
          category: null,
          serving_size_amount: 65.0,
          serving_size_unit: '1/2 cup',
        },
      ],
    },
    {
      date: '2025-09-05',
      menu_items: [
        {
          is_section_title: true,
          is_holiday: false,
          no_line_break: false,
          text: 'Pick One Entree',
          food: null,
          category: null,
          serving_size_amount: null,
          serving_size_unit: null,
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Homemade Spaghetti',
            description: '',
            image_url: 'https://assets.nutrislice.com/asset/serve/image/jpg/204329/thumbnail2',
            food_category: 'entree',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 450.0,
              g_fat: 12.0,
              g_saturated_fat: 4.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 41.0,
              g_carbs: 57.0,
              g_added_sugar: null,
              g_sugar: 2.0,
              mg_potassium: null,
              mg_sodium: 410.0,
              g_fiber: 18.0,
              g_protein: 20.0,
              mg_iron: 4.5,
              mg_calcium: 50.0,
              mg_vitamin_c: 10.0,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Grain',
                  help_text: 'This contains grain',
                  sort_order: 2,
                },
                {
                  name: 'Protein',
                  help_text: 'This contains protein',
                  sort_order: 3,
                },
              ],
            },
          },
          category: 'entree',
          serving_size_amount: 1028.0,
          serving_size_unit: '3/4 cup',
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: true,
          text: 'w/',
          food: null,
          category: null,
          serving_size_amount: null,
          serving_size_unit: null,
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: true,
          text: '',
          food: {
            name: 'Garlic Breadstick',
            description: '',
            image_url: null,
            food_category: '',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 100.0,
              g_fat: 3.5,
              g_saturated_fat: 0.5,
              g_trans_fat: 0.0,
              mg_cholesterol: 0.0,
              g_carbs: 15.0,
              g_added_sugar: null,
              g_sugar: 1.0,
              mg_potassium: null,
              mg_sodium: 95.0,
              g_fiber: 1.0,
              g_protein: 1.0,
              mg_iron: null,
              mg_calcium: null,
              mg_vitamin_c: null,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Grain',
                  help_text: 'This contains grain',
                  sort_order: 2,
                },
              ],
            },
          },
          category: null,
          serving_size_amount: 1.0,
          serving_size_unit: 'each',
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'SB & J Sandwich w/ String Cheese',
            description: '',
            image_url: 'https://assets.nutrislice.com/asset/serve/image/jpg/204744/thumbnail2',
            food_category: 'entree',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 490.0,
              g_fat: 25.0,
              g_saturated_fat: 6.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 20.0,
              g_carbs: 50.0,
              g_added_sugar: null,
              g_sugar: 19.0,
              mg_potassium: null,
              mg_sodium: 570.0,
              g_fiber: 6.0,
              g_protein: 19.0,
              mg_iron: 3.4,
              mg_calcium: 270.0,
              mg_vitamin_c: null,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Grain',
                  help_text: 'This contains grain',
                  sort_order: 2,
                },
                {
                  name: 'Protein',
                  help_text: 'This contains protein',
                  sort_order: 3,
                },
              ],
            },
          },
          category: 'entree',
          serving_size_amount: 1.0,
          serving_size_unit: 'each',
        },
        {
          is_section_title: true,
          is_holiday: false,
          no_line_break: false,
          text: 'Fruit & Vegetable Sides',
          food: null,
          category: null,
          serving_size_amount: null,
          serving_size_unit: null,
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Steamed Carrots',
            description: 'These crunchy carrots are loaded with vitamin A to keep your vision sharp!',
            image_url:
              'https://client-food-images.nutrislice.com/images/xQ/xQxnVjwrhxjttCzNXCegfE/1489180629_025405__2015-nutrislice-side-ALT1-steamed-carrots-1920x1080.jpg.1024x0_q85.jpg',
            food_category: '',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 30.0,
              g_fat: 0.0,
              g_saturated_fat: 0.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 0.0,
              g_carbs: 7.0,
              g_added_sugar: null,
              g_sugar: 4.0,
              mg_potassium: null,
              mg_sodium: 60.0,
              g_fiber: 3.0,
              g_protein: 1.0,
              mg_iron: 0.0,
              mg_calcium: 0.0,
              mg_vitamin_c: 1.0,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Vegetable',
                  help_text: 'This contains vegetables',
                  sort_order: 4,
                },
              ],
            },
          },
          category: null,
          serving_size_amount: 42.0,
          serving_size_unit: '1/2 cup',
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Fresh Green Beans',
            description: 'Fiber-filled and mighty\u2014green beans power your day!',
            image_url: null,
            food_category: 'vegetable',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 15.0,
              g_fat: 0.0,
              g_saturated_fat: 0.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 0.0,
              g_carbs: 3.0,
              g_added_sugar: null,
              g_sugar: 1.0,
              mg_potassium: null,
              mg_sodium: 0.0,
              g_fiber: 1.0,
              g_protein: 1.0,
              mg_iron: 0.4,
              mg_calcium: 20.0,
              mg_vitamin_c: 5.0,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Vegetable',
                  help_text: 'This contains vegetables',
                  sort_order: 4,
                },
              ],
            },
          },
          category: 'vegetable',
          serving_size_amount: 55.0,
          serving_size_unit: '1/2 cup',
        },
        {
          is_section_title: false,
          is_holiday: false,
          no_line_break: false,
          text: '',
          food: {
            name: 'Fresh Grapes',
            description: 'Fuel up with grapes\u2014fast, fun energy with no slowdown!',
            image_url: 'https://assets.nutrislice.com/asset/serve/image/jpg/21686/thumbnail2',
            food_category: '',
            has_nutrition_info: true,
            rounded_nutrition_info: {
              calories: 80.0,
              g_fat: 0.0,
              g_saturated_fat: 0.0,
              g_trans_fat: 0.0,
              mg_cholesterol: 0.0,
              g_carbs: 21.0,
              g_added_sugar: null,
              g_sugar: 18.0,
              mg_potassium: null,
              mg_sodium: 0.0,
              g_fiber: 1.0,
              g_protein: 1.0,
              mg_iron: 0.4,
              mg_calcium: 10.0,
              mg_vitamin_c: 4.0,
              iu_vitamin_a: null,
              re_vitamin_a: null,
              mcg_vitamin_a: null,
              mg_vitamin_d: null,
              mcg_vitamin_d: null,
            },
            icons: {
              myplate_icons: [
                {
                  name: 'Fruit',
                  help_text: 'This contains fruit',
                  sort_order: 1,
                },
              ],
            },
          },
          category: null,
          serving_size_amount: 4.0,
          serving_size_unit: '1/2 cup',
        },
      ],
    },
    {
      date: '2025-09-06',
      menu_items: [],
    },
  ],
};

export const empty_menu_data: Menu = {
  start_date: '2025-09-01',
  last_updated: '',
  days: [
    { date: '2025-08-31', menu_items: [] },
    { date: '2025-09-01', menu_items: [] },
    { date: '2025-09-02', menu_items: [] },
    { date: '2025-09-03', menu_items: [] },
    { date: '2025-09-04', menu_items: [] },
    { date: '2025-09-05', menu_items: [] },
    { date: '2025-09-06', menu_items: [] },
  ],
};
